services:
  almalinux9:
    build:
      context: .
      dockerfile: ./docker/almalinux9/Dockerfile
    container_name: almalinux9
    volumes:
      - ./scripts:/scripts:ro
      - ./samples:/samples:ro
      - ./outputs:/outputs:ro
    tty: true