services:
  almalinux9:
    build:
      context: .
      dockerfile: ./docker/almalinux9/Dockerfile
    container_name: almalinux9
    volumes:
      - ./scripts:/scripts
      - ./samples:/samples
      - ./outputs:/outputs
    tty: true